import MiniDrawer from "@/component/admin/dashboard";

export const metadata = {
  title: "Layout Admin",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <MiniDrawer>
        <div className="py-2">
          <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div className="overflow-hidden bg-white shadow-sm sm:rounded-lg">
              <div className="p-6 bg-gray-100">{children}</div>
            </div>
          </div>
        </div>
      </MiniDrawer>
    </div>
  );
}
