import DrawerAppBar from "@/component/user/dashboard";
import "./globals.css";
import Nav from "@/component/user/nav";
import Foot from "@/component/user/foot";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Nav />
      <div>{children}</div>
      {/* <Foot /> */}
    </>
  );
}
